const vehicleConfigs = {
	defaults: {
		body: 'jeep_yj',
		lift: 8,
		color: '#c81414',
		roughness: 0,
		addons: {},
		lighting: {},
		wheel_offset: 0,
		rim: 'konig_countersteer',
		rim_color: 'gloss_black',
		rim_color_secondary: 'gloss_black',
		rim_diameter: 24,
		rim_width: 16,
		tire: 'bfg_km2',
		tire_diameter: 40,
		tire_muddiness: 0,
		spare: true,
	},
	vehicles: {
		jeep_yj: {
			name: 'Jeep Wrangler (YJ)',
			make: 'Jeep',
			model: 'assets/models/vehicles/yj/yj.glb',
			wheel_offset: 0.7,
			wheelbase: 2.372,
			driverPosition: [0.45, 1.65, -0.5],
			default_addons: {},
			addons: {},
			lighting: {
				lightbar: [
					{
						name: 'Roof Light Bar',
						width: 36,
						rows: 1,
						color: 'white',
						position: [0, 1.34, 0.1],
						rotation: [0, 0, 0],
						curvature: 99,
					},
					{
						name: 'Ditch Lights',
						width: 2,
						rows: 2,
						color: 'white',
						position: [0.75, 0.9, 0.3],
						rotation: [0, 0.45, 0],
						pair: true,
					},
				],
			},
		},
		jeep_jk: {
			name: 'Jeep Wrangler (JKU)',
			make: 'Jeep',
			model: 'assets/models/vehicles/jk/jku.glb',
			wheel_offset: 0.75,
			wheelbase: 2.947,
			driverPosition: [0.45, 1.65, -0.5],
			default_addons: {},
			addons: {},
			lighting: {},
		},
		jeep_xj: {
			name: 'Jeep Cherokee (XJ)',
			make: 'Jeep',
			model: 'assets/models/vehicles/xj/xj.glb',
			wheel_offset: 0.7,
			wheelbase: 2.576,
			driverPosition: [0.45, 1.65, -0.5],
			default_addons: {},
			addons: {},
			lighting: {},
		},
	},
	wheels: {
		rims: {
			konig_countersteer: {
				make: 'Konig',
				name: 'Konig Countersteer',
				model: 'assets/models/wheels/konig_countersteer.glb',
				width: 0.5,
				od: 1,
			},
			ar_mojave: {
				make: 'American Racing',
				name: 'AR Mojave',
				model: 'assets/models/wheels/ar_mojave.glb',
				width: 0.5,
				od: 1,
			},
			cragar_soft_8: {
				make: 'Cragar',
				name: 'Cragar Soft 8',
				model: 'assets/models/wheels/cragar_soft_8.glb',
				width: 0.5,
				od: 1,
			},
			level_8_strike_6: {
				make: 'Level 8',
				name: 'Strike 6',
				model: 'assets/models/wheels/level_8_strike_6.glb',
				width: 0.5,
				od: 1,
			},
			moto_metal_mO951: {
				make: 'Moto Metal',
				name: 'MO951',
				model: 'assets/models/wheels/moto_metal_mO951.glb',
				width: 0.5,
				od: 1,
			},
			xd_grenade: {
				make: 'XD',
				name: 'Grenade',
				model: 'assets/models/wheels/xd_grenade.glb',
				width: 0.5,
				od: 1,
			},
			xd_machete: {
				make: 'XD',
				name: 'Machete',
				model: 'assets/models/wheels/xd_machete.glb',
				width: 0.5,
				od: 1,
			},
			toyota_trd: {
				make: 'Toyota',
				name: 'TRD',
				model: 'assets/models/wheels/toyota_trd.glb',
				width: 0.5,
				od: 1,
			},
			ford_bronco: {
				make: 'Ford',
				name: 'Ford Bronco',
				model: 'assets/models/wheels/ford_bronco.glb',
				width: 0.5,
				od: 1,
			},
			toyota_4runner: {
				make: 'Toyota',
				name: '4Runner',
				model: 'assets/models/wheels/toyota_4runner.glb',
				width: 0.5,
				od: 1,
			},
		},
		tires: {
			bfg_km2: {
				make: 'BFGoodrich',
				name: 'BFGoodrich KM2',
				model: 'assets/models/wheels/tires/bfg_km2.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			bfg_km3: {
				make: 'BFGoodrich',
				name: 'BFGoodrich KM3',
				model: 'assets/models/wheels/tires/bfg_km3.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			bfg_at: {
				make: 'BFGoodrich',
				name: 'BFGoodrich All-Terrain T/A KO2',
				model: 'assets/models/wheels/tires/bfg_at.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			maxxis_trepador: {
				make: 'Maxxis',
				name: 'Trepador',
				model: 'assets/models/wheels/tires/maxxis_trepador.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			mud_grappler: {
				make: 'Nitto',
				name: 'Mud Grappler',
				model: 'assets/models/wheels/tires/mud_grappler.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			thornbird: {
				make: 'Interco',
				name: 'Super Swamper Thornbird',
				model: 'assets/models/wheels/tires/thornbird.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
			toyo_open_country_mt: {
				make: 'Toyo',
				name: 'Open Country M/T',
				model: 'assets/models/wheels/tires/toyo_open_country_mt.glb',
				width: 0.245,
				od: 0.837,
				id: 0.44,
			},
		},
	},
}

export default vehicleConfigs
